seq_dataset 214
seq_dataset_val 234
Train epoch 1/200
  0% 0/1000 [00:00<?, ?it/s]  0% 0/1000 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 277, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 193, in main
    closs, rloss, loss = model.step(epoch, dataset,anchors, i,  train=True)
  File "/home/zuern/SiamRPN-PyTorch/train/net.py", line 71, in step
    pred_score, pred_regression = self.net(template_rgb, detection_rgb, template_ir, detection_ir)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/SiamRPN-PyTorch/tracking/network.py", line 243, in forward
    kernel_score = self.conv_cls1(template_feature).view(N, 2 * self.anchor_num, 256, 4, 4)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size 2560 256 3 3, expected input[32, 512, 6, 6] to have 256 channels, but got 512 channels instead
