seq_dataset 214
seq_dataset_val 234
Train epoch 1/200
  0% 0/1000 [00:00<?, ?it/s]  0% 0/1000 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 277, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 193, in main
    closs, rloss, loss = model.step(epoch, dataset,anchors, i,  train=True)
  File "/home/zuern/SiamRPN-PyTorch/train/net.py", line 71, in step
    pred_score, pred_regression = self.net(template_rgb, detection_rgb, template_ir, detection_ir)
  File "/home/zuern/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zuern/SiamRPN-PyTorch/tracking/network.py", line 251, in forward
    kernel_score = self.conv_cls1(template_feature).view(N, 2 * self.anchor_num, 256, 4, 4)
RuntimeError: shape '[32, 10, 256, 4, 4]' is invalid for input of size 2621440
