seq_dataset 214
seq_dataset_val 234
Traceback (most recent call last):
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 277, in <module>
    main()
  File "/home/zuern/SiamRPN-PyTorch/train/train_siamrpn.py", line 167, in main
    train_val_plot = SavePlot(exp_name_dir, 'train_val_plot')
  File "/home/zuern/SiamRPN-PyTorch/train/util.py", line 186, in __init__
    self.show)
  File "/home/zuern/SiamRPN-PyTorch/train/util.py", line 233, in plot
    self.plt.savefig("{}/{}.png".format(exp_name_dir, name))
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/zuern/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 392, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'experiments/SiamRPN_RGB/train_val_plot.png'
